/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VisualSearchRouteImport } from './routes/visual-search'
import { Route as SocialMediaViralsRouteImport } from './routes/social-media-virals'
import { Route as RewardsRouteImport } from './routes/rewards'
import { Route as MusicMediaRouteImport } from './routes/music-media'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as LookbookRouteImport } from './routes/lookbook'
import { Route as FrassKicksRouteImport } from './routes/frass-kicks'
import { Route as FrassDripRouteImport } from './routes/frass-drip'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CapsulesRouteImport } from './routes/capsules'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as BareDripRouteImport } from './routes/bare-drip'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AfroDesignersRouteImport } from './routes/afro-designers'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SocialMediaViralsIndexRouteImport } from './routes/social-media-virals.index'
import { Route as LookbookIndexRouteImport } from './routes/lookbook.index'
import { Route as FrassKicksIndexRouteImport } from './routes/frass-kicks.index'
import { Route as FrassDripIndexRouteImport } from './routes/frass-drip.index'
import { Route as CapsulesIndexRouteImport } from './routes/capsules.index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BareDripIndexRouteImport } from './routes/bare-drip.index'
import { Route as AfroDesignersIndexRouteImport } from './routes/afro-designers.index'
import { Route as SocialMediaViralsCategoryRouteImport } from './routes/social-media-virals.$category'
import { Route as ProductHandleRouteImport } from './routes/product.$handle'
import { Route as LookbookStoryRouteImport } from './routes/lookbook.$story'
import { Route as FrassKicksWomenRouteImport } from './routes/frass-kicks.women'
import { Route as FrassKicksMenRouteImport } from './routes/frass-kicks.men'
import { Route as FrassDripWomenRouteImport } from './routes/frass-drip.women'
import { Route as FrassDripMenRouteImport } from './routes/frass-drip.men'
import { Route as CollectionHandleRouteImport } from './routes/collection.$handle'
import { Route as CapsulesHandleRouteImport } from './routes/capsules.$handle'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as BareDripWomenRouteImport } from './routes/bare-drip.women'
import { Route as BareDripMenRouteImport } from './routes/bare-drip.men'
import { Route as ApiTtsRouteImport } from './routes/api/tts'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AfroDesignersDesignersRouteImport } from './routes/afro-designers.designers'
import { Route as AuthenticatedWorkspaceRouteImport } from './routes/_authenticated/workspace'
import { Route as AuthenticatedTryOnRouteImport } from './routes/_authenticated/try-on'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedFrassyRouteImport } from './routes/_authenticated/frassy'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as FrassDripWomenIndexRouteImport } from './routes/frass-drip.women.index'
import { Route as FrassDripMenIndexRouteImport } from './routes/frass-drip.men.index'
import { Route as BareDripWomenIndexRouteImport } from './routes/bare-drip.women.index'
import { Route as BareDripMenIndexRouteImport } from './routes/bare-drip.men.index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as SocialMediaViralsCategorySubRouteImport } from './routes/social-media-virals.$category.$sub'
import { Route as FrassDripWomenCategoryRouteImport } from './routes/frass-drip.women.$category'
import { Route as FrassDripMenCategoryRouteImport } from './routes/frass-drip.men.$category'
import { Route as BareDripWomenCategoryRouteImport } from './routes/bare-drip.women.$category'
import { Route as BareDripMenCategoryRouteImport } from './routes/bare-drip.men.$category'
import { Route as AfroDesignersDesignersSlugRouteImport } from './routes/afro-designers.designers.$slug'
import { Route as AfroDesignersCollectionsSlugRouteImport } from './routes/afro-designers.collections.$slug'
import { Route as AuthenticatedAdminVisualIndexRouteImport } from './routes/_authenticated/admin.visual-index'
import { Route as AuthenticatedAdminViralsRouteImport } from './routes/_authenticated/admin.virals'
import { Route as AuthenticatedAdminTextRouteImport } from './routes/_authenticated/admin.text'
import { Route as AuthenticatedAdminRolesRouteImport } from './routes/_authenticated/admin.roles'
import { Route as AuthenticatedAdminPartnerVendorsRouteImport } from './routes/_authenticated/admin.partner-vendors'
import { Route as AuthenticatedAdminMediaRouteImport } from './routes/_authenticated/admin.media'
import { Route as AuthenticatedAdminImagesRouteImport } from './routes/_authenticated/admin.images'
import { Route as AuthenticatedAdminCjImportRouteImport } from './routes/_authenticated/admin.cj-import'
import { Route as AuthenticatedAdminCapsulesRouteImport } from './routes/_authenticated/admin.capsules'
import { Route as AuthenticatedAdminBlogRouteImport } from './routes/_authenticated/admin.blog'
import { Route as AuthenticatedAdminApprovalsRouteImport } from './routes/_authenticated/admin.approvals'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as SocialMediaViralsCategorySubProductRouteImport } from './routes/social-media-virals.$category.$sub.$product'

const VisualSearchRoute = VisualSearchRouteImport.update({
  id: '/visual-search',
  path: '/visual-search',
  getParentRoute: () => rootRouteImport,
} as any)
const SocialMediaViralsRoute = SocialMediaViralsRouteImport.update({
  id: '/social-media-virals',
  path: '/social-media-virals',
  getParentRoute: () => rootRouteImport,
} as any)
const RewardsRoute = RewardsRouteImport.update({
  id: '/rewards',
  path: '/rewards',
  getParentRoute: () => rootRouteImport,
} as any)
const MusicMediaRoute = MusicMediaRouteImport.update({
  id: '/music-media',
  path: '/music-media',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const LookbookRoute = LookbookRouteImport.update({
  id: '/lookbook',
  path: '/lookbook',
  getParentRoute: () => rootRouteImport,
} as any)
const FrassKicksRoute = FrassKicksRouteImport.update({
  id: '/frass-kicks',
  path: '/frass-kicks',
  getParentRoute: () => rootRouteImport,
} as any)
const FrassDripRoute = FrassDripRouteImport.update({
  id: '/frass-drip',
  path: '/frass-drip',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CapsulesRoute = CapsulesRouteImport.update({
  id: '/capsules',
  path: '/capsules',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const BareDripRoute = BareDripRouteImport.update({
  id: '/bare-drip',
  path: '/bare-drip',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AfroDesignersRoute = AfroDesignersRouteImport.update({
  id: '/afro-designers',
  path: '/afro-designers',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SocialMediaViralsIndexRoute = SocialMediaViralsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SocialMediaViralsRoute,
} as any)
const LookbookIndexRoute = LookbookIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LookbookRoute,
} as any)
const FrassKicksIndexRoute = FrassKicksIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FrassKicksRoute,
} as any)
const FrassDripIndexRoute = FrassDripIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FrassDripRoute,
} as any)
const CapsulesIndexRoute = CapsulesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CapsulesRoute,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BlogRoute,
} as any)
const BareDripIndexRoute = BareDripIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BareDripRoute,
} as any)
const AfroDesignersIndexRoute = AfroDesignersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AfroDesignersRoute,
} as any)
const SocialMediaViralsCategoryRoute =
  SocialMediaViralsCategoryRouteImport.update({
    id: '/$category',
    path: '/$category',
    getParentRoute: () => SocialMediaViralsRoute,
  } as any)
const ProductHandleRoute = ProductHandleRouteImport.update({
  id: '/product/$handle',
  path: '/product/$handle',
  getParentRoute: () => rootRouteImport,
} as any)
const LookbookStoryRoute = LookbookStoryRouteImport.update({
  id: '/$story',
  path: '/$story',
  getParentRoute: () => LookbookRoute,
} as any)
const FrassKicksWomenRoute = FrassKicksWomenRouteImport.update({
  id: '/women',
  path: '/women',
  getParentRoute: () => FrassKicksRoute,
} as any)
const FrassKicksMenRoute = FrassKicksMenRouteImport.update({
  id: '/men',
  path: '/men',
  getParentRoute: () => FrassKicksRoute,
} as any)
const FrassDripWomenRoute = FrassDripWomenRouteImport.update({
  id: '/women',
  path: '/women',
  getParentRoute: () => FrassDripRoute,
} as any)
const FrassDripMenRoute = FrassDripMenRouteImport.update({
  id: '/men',
  path: '/men',
  getParentRoute: () => FrassDripRoute,
} as any)
const CollectionHandleRoute = CollectionHandleRouteImport.update({
  id: '/collection/$handle',
  path: '/collection/$handle',
  getParentRoute: () => rootRouteImport,
} as any)
const CapsulesHandleRoute = CapsulesHandleRouteImport.update({
  id: '/$handle',
  path: '/$handle',
  getParentRoute: () => CapsulesRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const BareDripWomenRoute = BareDripWomenRouteImport.update({
  id: '/women',
  path: '/women',
  getParentRoute: () => BareDripRoute,
} as any)
const BareDripMenRoute = BareDripMenRouteImport.update({
  id: '/men',
  path: '/men',
  getParentRoute: () => BareDripRoute,
} as any)
const ApiTtsRoute = ApiTtsRouteImport.update({
  id: '/api/tts',
  path: '/api/tts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AfroDesignersDesignersRoute = AfroDesignersDesignersRouteImport.update({
  id: '/designers',
  path: '/designers',
  getParentRoute: () => AfroDesignersRoute,
} as any)
const AuthenticatedWorkspaceRoute = AuthenticatedWorkspaceRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTryOnRoute = AuthenticatedTryOnRouteImport.update({
  id: '/try-on',
  path: '/try-on',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFrassyRoute = AuthenticatedFrassyRouteImport.update({
  id: '/frassy',
  path: '/frassy',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const FrassDripWomenIndexRoute = FrassDripWomenIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FrassDripWomenRoute,
} as any)
const FrassDripMenIndexRoute = FrassDripMenIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FrassDripMenRoute,
} as any)
const BareDripWomenIndexRoute = BareDripWomenIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BareDripWomenRoute,
} as any)
const BareDripMenIndexRoute = BareDripMenIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BareDripMenRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const SocialMediaViralsCategorySubRoute =
  SocialMediaViralsCategorySubRouteImport.update({
    id: '/$sub',
    path: '/$sub',
    getParentRoute: () => SocialMediaViralsCategoryRoute,
  } as any)
const FrassDripWomenCategoryRoute = FrassDripWomenCategoryRouteImport.update({
  id: '/$category',
  path: '/$category',
  getParentRoute: () => FrassDripWomenRoute,
} as any)
const FrassDripMenCategoryRoute = FrassDripMenCategoryRouteImport.update({
  id: '/$category',
  path: '/$category',
  getParentRoute: () => FrassDripMenRoute,
} as any)
const BareDripWomenCategoryRoute = BareDripWomenCategoryRouteImport.update({
  id: '/$category',
  path: '/$category',
  getParentRoute: () => BareDripWomenRoute,
} as any)
const BareDripMenCategoryRoute = BareDripMenCategoryRouteImport.update({
  id: '/$category',
  path: '/$category',
  getParentRoute: () => BareDripMenRoute,
} as any)
const AfroDesignersDesignersSlugRoute =
  AfroDesignersDesignersSlugRouteImport.update({
    id: '/$slug',
    path: '/$slug',
    getParentRoute: () => AfroDesignersDesignersRoute,
  } as any)
const AfroDesignersCollectionsSlugRoute =
  AfroDesignersCollectionsSlugRouteImport.update({
    id: '/collections/$slug',
    path: '/collections/$slug',
    getParentRoute: () => AfroDesignersRoute,
  } as any)
const AuthenticatedAdminVisualIndexRoute =
  AuthenticatedAdminVisualIndexRouteImport.update({
    id: '/visual-index',
    path: '/visual-index',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminViralsRoute =
  AuthenticatedAdminViralsRouteImport.update({
    id: '/virals',
    path: '/virals',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminTextRoute = AuthenticatedAdminTextRouteImport.update({
  id: '/text',
  path: '/text',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminRolesRoute = AuthenticatedAdminRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminPartnerVendorsRoute =
  AuthenticatedAdminPartnerVendorsRouteImport.update({
    id: '/partner-vendors',
    path: '/partner-vendors',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminMediaRoute = AuthenticatedAdminMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminImagesRoute =
  AuthenticatedAdminImagesRouteImport.update({
    id: '/images',
    path: '/images',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCjImportRoute =
  AuthenticatedAdminCjImportRouteImport.update({
    id: '/cj-import',
    path: '/cj-import',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCapsulesRoute =
  AuthenticatedAdminCapsulesRouteImport.update({
    id: '/capsules',
    path: '/capsules',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminBlogRoute = AuthenticatedAdminBlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminApprovalsRoute =
  AuthenticatedAdminApprovalsRouteImport.update({
    id: '/approvals',
    path: '/approvals',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const SocialMediaViralsCategorySubProductRoute =
  SocialMediaViralsCategorySubProductRouteImport.update({
    id: '/$product',
    path: '/$product',
    getParentRoute: () => SocialMediaViralsCategorySubRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/afro-designers': typeof AfroDesignersRouteWithChildren
  '/auth': typeof AuthRoute
  '/bare-drip': typeof BareDripRouteWithChildren
  '/blog': typeof BlogRouteWithChildren
  '/capsules': typeof CapsulesRouteWithChildren
  '/checkout': typeof CheckoutRoute
  '/frass-drip': typeof FrassDripRouteWithChildren
  '/frass-kicks': typeof FrassKicksRouteWithChildren
  '/lookbook': typeof LookbookRouteWithChildren
  '/mcp': typeof McpRoute
  '/music-media': typeof MusicMediaRoute
  '/rewards': typeof RewardsRoute
  '/social-media-virals': typeof SocialMediaViralsRouteWithChildren
  '/visual-search': typeof VisualSearchRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/frassy': typeof AuthenticatedFrassyRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/try-on': typeof AuthenticatedTryOnRoute
  '/workspace': typeof AuthenticatedWorkspaceRoute
  '/afro-designers/designers': typeof AfroDesignersDesignersRouteWithChildren
  '/api/chat': typeof ApiChatRoute
  '/api/tts': typeof ApiTtsRoute
  '/bare-drip/men': typeof BareDripMenRouteWithChildren
  '/bare-drip/women': typeof BareDripWomenRouteWithChildren
  '/blog/$slug': typeof BlogSlugRoute
  '/capsules/$handle': typeof CapsulesHandleRoute
  '/collection/$handle': typeof CollectionHandleRoute
  '/frass-drip/men': typeof FrassDripMenRouteWithChildren
  '/frass-drip/women': typeof FrassDripWomenRouteWithChildren
  '/frass-kicks/men': typeof FrassKicksMenRoute
  '/frass-kicks/women': typeof FrassKicksWomenRoute
  '/lookbook/$story': typeof LookbookStoryRoute
  '/product/$handle': typeof ProductHandleRoute
  '/social-media-virals/$category': typeof SocialMediaViralsCategoryRouteWithChildren
  '/afro-designers/': typeof AfroDesignersIndexRoute
  '/bare-drip/': typeof BareDripIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/capsules/': typeof CapsulesIndexRoute
  '/frass-drip/': typeof FrassDripIndexRoute
  '/frass-kicks/': typeof FrassKicksIndexRoute
  '/lookbook/': typeof LookbookIndexRoute
  '/social-media-virals/': typeof SocialMediaViralsIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/admin/approvals': typeof AuthenticatedAdminApprovalsRoute
  '/admin/blog': typeof AuthenticatedAdminBlogRoute
  '/admin/capsules': typeof AuthenticatedAdminCapsulesRoute
  '/admin/cj-import': typeof AuthenticatedAdminCjImportRoute
  '/admin/images': typeof AuthenticatedAdminImagesRoute
  '/admin/media': typeof AuthenticatedAdminMediaRoute
  '/admin/partner-vendors': typeof AuthenticatedAdminPartnerVendorsRoute
  '/admin/roles': typeof AuthenticatedAdminRolesRoute
  '/admin/text': typeof AuthenticatedAdminTextRoute
  '/admin/virals': typeof AuthenticatedAdminViralsRoute
  '/admin/visual-index': typeof AuthenticatedAdminVisualIndexRoute
  '/afro-designers/collections/$slug': typeof AfroDesignersCollectionsSlugRoute
  '/afro-designers/designers/$slug': typeof AfroDesignersDesignersSlugRoute
  '/bare-drip/men/$category': typeof BareDripMenCategoryRoute
  '/bare-drip/women/$category': typeof BareDripWomenCategoryRoute
  '/frass-drip/men/$category': typeof FrassDripMenCategoryRoute
  '/frass-drip/women/$category': typeof FrassDripWomenCategoryRoute
  '/social-media-virals/$category/$sub': typeof SocialMediaViralsCategorySubRouteWithChildren
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/bare-drip/men/': typeof BareDripMenIndexRoute
  '/bare-drip/women/': typeof BareDripWomenIndexRoute
  '/frass-drip/men/': typeof FrassDripMenIndexRoute
  '/frass-drip/women/': typeof FrassDripWomenIndexRoute
  '/social-media-virals/$category/$sub/$product': typeof SocialMediaViralsCategorySubProductRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/checkout': typeof CheckoutRoute
  '/mcp': typeof McpRoute
  '/music-media': typeof MusicMediaRoute
  '/rewards': typeof RewardsRoute
  '/visual-search': typeof VisualSearchRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/frassy': typeof AuthenticatedFrassyRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/try-on': typeof AuthenticatedTryOnRoute
  '/workspace': typeof AuthenticatedWorkspaceRoute
  '/afro-designers/designers': typeof AfroDesignersDesignersRouteWithChildren
  '/api/chat': typeof ApiChatRoute
  '/api/tts': typeof ApiTtsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/capsules/$handle': typeof CapsulesHandleRoute
  '/collection/$handle': typeof CollectionHandleRoute
  '/frass-kicks/men': typeof FrassKicksMenRoute
  '/frass-kicks/women': typeof FrassKicksWomenRoute
  '/lookbook/$story': typeof LookbookStoryRoute
  '/product/$handle': typeof ProductHandleRoute
  '/social-media-virals/$category': typeof SocialMediaViralsCategoryRouteWithChildren
  '/afro-designers': typeof AfroDesignersIndexRoute
  '/bare-drip': typeof BareDripIndexRoute
  '/blog': typeof BlogIndexRoute
  '/capsules': typeof CapsulesIndexRoute
  '/frass-drip': typeof FrassDripIndexRoute
  '/frass-kicks': typeof FrassKicksIndexRoute
  '/lookbook': typeof LookbookIndexRoute
  '/social-media-virals': typeof SocialMediaViralsIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/admin/approvals': typeof AuthenticatedAdminApprovalsRoute
  '/admin/blog': typeof AuthenticatedAdminBlogRoute
  '/admin/capsules': typeof AuthenticatedAdminCapsulesRoute
  '/admin/cj-import': typeof AuthenticatedAdminCjImportRoute
  '/admin/images': typeof AuthenticatedAdminImagesRoute
  '/admin/media': typeof AuthenticatedAdminMediaRoute
  '/admin/partner-vendors': typeof AuthenticatedAdminPartnerVendorsRoute
  '/admin/roles': typeof AuthenticatedAdminRolesRoute
  '/admin/text': typeof AuthenticatedAdminTextRoute
  '/admin/virals': typeof AuthenticatedAdminViralsRoute
  '/admin/visual-index': typeof AuthenticatedAdminVisualIndexRoute
  '/afro-designers/collections/$slug': typeof AfroDesignersCollectionsSlugRoute
  '/afro-designers/designers/$slug': typeof AfroDesignersDesignersSlugRoute
  '/bare-drip/men/$category': typeof BareDripMenCategoryRoute
  '/bare-drip/women/$category': typeof BareDripWomenCategoryRoute
  '/frass-drip/men/$category': typeof FrassDripMenCategoryRoute
  '/frass-drip/women/$category': typeof FrassDripWomenCategoryRoute
  '/social-media-virals/$category/$sub': typeof SocialMediaViralsCategorySubRouteWithChildren
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/bare-drip/men': typeof BareDripMenIndexRoute
  '/bare-drip/women': typeof BareDripWomenIndexRoute
  '/frass-drip/men': typeof FrassDripMenIndexRoute
  '/frass-drip/women': typeof FrassDripWomenIndexRoute
  '/social-media-virals/$category/$sub/$product': typeof SocialMediaViralsCategorySubProductRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/afro-designers': typeof AfroDesignersRouteWithChildren
  '/auth': typeof AuthRoute
  '/bare-drip': typeof BareDripRouteWithChildren
  '/blog': typeof BlogRouteWithChildren
  '/capsules': typeof CapsulesRouteWithChildren
  '/checkout': typeof CheckoutRoute
  '/frass-drip': typeof FrassDripRouteWithChildren
  '/frass-kicks': typeof FrassKicksRouteWithChildren
  '/lookbook': typeof LookbookRouteWithChildren
  '/mcp': typeof McpRoute
  '/music-media': typeof MusicMediaRoute
  '/rewards': typeof RewardsRoute
  '/social-media-virals': typeof SocialMediaViralsRouteWithChildren
  '/visual-search': typeof VisualSearchRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/frassy': typeof AuthenticatedFrassyRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/try-on': typeof AuthenticatedTryOnRoute
  '/_authenticated/workspace': typeof AuthenticatedWorkspaceRoute
  '/afro-designers/designers': typeof AfroDesignersDesignersRouteWithChildren
  '/api/chat': typeof ApiChatRoute
  '/api/tts': typeof ApiTtsRoute
  '/bare-drip/men': typeof BareDripMenRouteWithChildren
  '/bare-drip/women': typeof BareDripWomenRouteWithChildren
  '/blog/$slug': typeof BlogSlugRoute
  '/capsules/$handle': typeof CapsulesHandleRoute
  '/collection/$handle': typeof CollectionHandleRoute
  '/frass-drip/men': typeof FrassDripMenRouteWithChildren
  '/frass-drip/women': typeof FrassDripWomenRouteWithChildren
  '/frass-kicks/men': typeof FrassKicksMenRoute
  '/frass-kicks/women': typeof FrassKicksWomenRoute
  '/lookbook/$story': typeof LookbookStoryRoute
  '/product/$handle': typeof ProductHandleRoute
  '/social-media-virals/$category': typeof SocialMediaViralsCategoryRouteWithChildren
  '/afro-designers/': typeof AfroDesignersIndexRoute
  '/bare-drip/': typeof BareDripIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/capsules/': typeof CapsulesIndexRoute
  '/frass-drip/': typeof FrassDripIndexRoute
  '/frass-kicks/': typeof FrassKicksIndexRoute
  '/lookbook/': typeof LookbookIndexRoute
  '/social-media-virals/': typeof SocialMediaViralsIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/_authenticated/admin/approvals': typeof AuthenticatedAdminApprovalsRoute
  '/_authenticated/admin/blog': typeof AuthenticatedAdminBlogRoute
  '/_authenticated/admin/capsules': typeof AuthenticatedAdminCapsulesRoute
  '/_authenticated/admin/cj-import': typeof AuthenticatedAdminCjImportRoute
  '/_authenticated/admin/images': typeof AuthenticatedAdminImagesRoute
  '/_authenticated/admin/media': typeof AuthenticatedAdminMediaRoute
  '/_authenticated/admin/partner-vendors': typeof AuthenticatedAdminPartnerVendorsRoute
  '/_authenticated/admin/roles': typeof AuthenticatedAdminRolesRoute
  '/_authenticated/admin/text': typeof AuthenticatedAdminTextRoute
  '/_authenticated/admin/virals': typeof AuthenticatedAdminViralsRoute
  '/_authenticated/admin/visual-index': typeof AuthenticatedAdminVisualIndexRoute
  '/afro-designers/collections/$slug': typeof AfroDesignersCollectionsSlugRoute
  '/afro-designers/designers/$slug': typeof AfroDesignersDesignersSlugRoute
  '/bare-drip/men/$category': typeof BareDripMenCategoryRoute
  '/bare-drip/women/$category': typeof BareDripWomenCategoryRoute
  '/frass-drip/men/$category': typeof FrassDripMenCategoryRoute
  '/frass-drip/women/$category': typeof FrassDripWomenCategoryRoute
  '/social-media-virals/$category/$sub': typeof SocialMediaViralsCategorySubRouteWithChildren
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/bare-drip/men/': typeof BareDripMenIndexRoute
  '/bare-drip/women/': typeof BareDripWomenIndexRoute
  '/frass-drip/men/': typeof FrassDripMenIndexRoute
  '/frass-drip/women/': typeof FrassDripWomenIndexRoute
  '/social-media-virals/$category/$sub/$product': typeof SocialMediaViralsCategorySubProductRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/afro-designers'
    | '/auth'
    | '/bare-drip'
    | '/blog'
    | '/capsules'
    | '/checkout'
    | '/frass-drip'
    | '/frass-kicks'
    | '/lookbook'
    | '/mcp'
    | '/music-media'
    | '/rewards'
    | '/social-media-virals'
    | '/visual-search'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin'
    | '/frassy'
    | '/notifications'
    | '/try-on'
    | '/workspace'
    | '/afro-designers/designers'
    | '/api/chat'
    | '/api/tts'
    | '/bare-drip/men'
    | '/bare-drip/women'
    | '/blog/$slug'
    | '/capsules/$handle'
    | '/collection/$handle'
    | '/frass-drip/men'
    | '/frass-drip/women'
    | '/frass-kicks/men'
    | '/frass-kicks/women'
    | '/lookbook/$story'
    | '/product/$handle'
    | '/social-media-virals/$category'
    | '/afro-designers/'
    | '/bare-drip/'
    | '/blog/'
    | '/capsules/'
    | '/frass-drip/'
    | '/frass-kicks/'
    | '/lookbook/'
    | '/social-media-virals/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/admin/approvals'
    | '/admin/blog'
    | '/admin/capsules'
    | '/admin/cj-import'
    | '/admin/images'
    | '/admin/media'
    | '/admin/partner-vendors'
    | '/admin/roles'
    | '/admin/text'
    | '/admin/virals'
    | '/admin/visual-index'
    | '/afro-designers/collections/$slug'
    | '/afro-designers/designers/$slug'
    | '/bare-drip/men/$category'
    | '/bare-drip/women/$category'
    | '/frass-drip/men/$category'
    | '/frass-drip/women/$category'
    | '/social-media-virals/$category/$sub'
    | '/admin/'
    | '/bare-drip/men/'
    | '/bare-drip/women/'
    | '/frass-drip/men/'
    | '/frass-drip/women/'
    | '/social-media-virals/$category/$sub/$product'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/checkout'
    | '/mcp'
    | '/music-media'
    | '/rewards'
    | '/visual-search'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/frassy'
    | '/notifications'
    | '/try-on'
    | '/workspace'
    | '/afro-designers/designers'
    | '/api/chat'
    | '/api/tts'
    | '/blog/$slug'
    | '/capsules/$handle'
    | '/collection/$handle'
    | '/frass-kicks/men'
    | '/frass-kicks/women'
    | '/lookbook/$story'
    | '/product/$handle'
    | '/social-media-virals/$category'
    | '/afro-designers'
    | '/bare-drip'
    | '/blog'
    | '/capsules'
    | '/frass-drip'
    | '/frass-kicks'
    | '/lookbook'
    | '/social-media-virals'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/admin/approvals'
    | '/admin/blog'
    | '/admin/capsules'
    | '/admin/cj-import'
    | '/admin/images'
    | '/admin/media'
    | '/admin/partner-vendors'
    | '/admin/roles'
    | '/admin/text'
    | '/admin/virals'
    | '/admin/visual-index'
    | '/afro-designers/collections/$slug'
    | '/afro-designers/designers/$slug'
    | '/bare-drip/men/$category'
    | '/bare-drip/women/$category'
    | '/frass-drip/men/$category'
    | '/frass-drip/women/$category'
    | '/social-media-virals/$category/$sub'
    | '/admin'
    | '/bare-drip/men'
    | '/bare-drip/women'
    | '/frass-drip/men'
    | '/frass-drip/women'
    | '/social-media-virals/$category/$sub/$product'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/afro-designers'
    | '/auth'
    | '/bare-drip'
    | '/blog'
    | '/capsules'
    | '/checkout'
    | '/frass-drip'
    | '/frass-kicks'
    | '/lookbook'
    | '/mcp'
    | '/music-media'
    | '/rewards'
    | '/social-media-virals'
    | '/visual-search'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/_authenticated/admin'
    | '/_authenticated/frassy'
    | '/_authenticated/notifications'
    | '/_authenticated/try-on'
    | '/_authenticated/workspace'
    | '/afro-designers/designers'
    | '/api/chat'
    | '/api/tts'
    | '/bare-drip/men'
    | '/bare-drip/women'
    | '/blog/$slug'
    | '/capsules/$handle'
    | '/collection/$handle'
    | '/frass-drip/men'
    | '/frass-drip/women'
    | '/frass-kicks/men'
    | '/frass-kicks/women'
    | '/lookbook/$story'
    | '/product/$handle'
    | '/social-media-virals/$category'
    | '/afro-designers/'
    | '/bare-drip/'
    | '/blog/'
    | '/capsules/'
    | '/frass-drip/'
    | '/frass-kicks/'
    | '/lookbook/'
    | '/social-media-virals/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/_authenticated/admin/approvals'
    | '/_authenticated/admin/blog'
    | '/_authenticated/admin/capsules'
    | '/_authenticated/admin/cj-import'
    | '/_authenticated/admin/images'
    | '/_authenticated/admin/media'
    | '/_authenticated/admin/partner-vendors'
    | '/_authenticated/admin/roles'
    | '/_authenticated/admin/text'
    | '/_authenticated/admin/virals'
    | '/_authenticated/admin/visual-index'
    | '/afro-designers/collections/$slug'
    | '/afro-designers/designers/$slug'
    | '/bare-drip/men/$category'
    | '/bare-drip/women/$category'
    | '/frass-drip/men/$category'
    | '/frass-drip/women/$category'
    | '/social-media-virals/$category/$sub'
    | '/_authenticated/admin/'
    | '/bare-drip/men/'
    | '/bare-drip/women/'
    | '/frass-drip/men/'
    | '/frass-drip/women/'
    | '/social-media-virals/$category/$sub/$product'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AfroDesignersRoute: typeof AfroDesignersRouteWithChildren
  AuthRoute: typeof AuthRoute
  BareDripRoute: typeof BareDripRouteWithChildren
  BlogRoute: typeof BlogRouteWithChildren
  CapsulesRoute: typeof CapsulesRouteWithChildren
  CheckoutRoute: typeof CheckoutRoute
  FrassDripRoute: typeof FrassDripRouteWithChildren
  FrassKicksRoute: typeof FrassKicksRouteWithChildren
  LookbookRoute: typeof LookbookRouteWithChildren
  McpRoute: typeof McpRoute
  MusicMediaRoute: typeof MusicMediaRoute
  RewardsRoute: typeof RewardsRoute
  SocialMediaViralsRoute: typeof SocialMediaViralsRouteWithChildren
  VisualSearchRoute: typeof VisualSearchRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiTtsRoute: typeof ApiTtsRoute
  CollectionHandleRoute: typeof CollectionHandleRoute
  ProductHandleRoute: typeof ProductHandleRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/visual-search': {
      id: '/visual-search'
      path: '/visual-search'
      fullPath: '/visual-search'
      preLoaderRoute: typeof VisualSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/social-media-virals': {
      id: '/social-media-virals'
      path: '/social-media-virals'
      fullPath: '/social-media-virals'
      preLoaderRoute: typeof SocialMediaViralsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rewards': {
      id: '/rewards'
      path: '/rewards'
      fullPath: '/rewards'
      preLoaderRoute: typeof RewardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/music-media': {
      id: '/music-media'
      path: '/music-media'
      fullPath: '/music-media'
      preLoaderRoute: typeof MusicMediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lookbook': {
      id: '/lookbook'
      path: '/lookbook'
      fullPath: '/lookbook'
      preLoaderRoute: typeof LookbookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/frass-kicks': {
      id: '/frass-kicks'
      path: '/frass-kicks'
      fullPath: '/frass-kicks'
      preLoaderRoute: typeof FrassKicksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/frass-drip': {
      id: '/frass-drip'
      path: '/frass-drip'
      fullPath: '/frass-drip'
      preLoaderRoute: typeof FrassDripRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/capsules': {
      id: '/capsules'
      path: '/capsules'
      fullPath: '/capsules'
      preLoaderRoute: typeof CapsulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bare-drip': {
      id: '/bare-drip'
      path: '/bare-drip'
      fullPath: '/bare-drip'
      preLoaderRoute: typeof BareDripRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/afro-designers': {
      id: '/afro-designers'
      path: '/afro-designers'
      fullPath: '/afro-designers'
      preLoaderRoute: typeof AfroDesignersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/social-media-virals/': {
      id: '/social-media-virals/'
      path: '/'
      fullPath: '/social-media-virals/'
      preLoaderRoute: typeof SocialMediaViralsIndexRouteImport
      parentRoute: typeof SocialMediaViralsRoute
    }
    '/lookbook/': {
      id: '/lookbook/'
      path: '/'
      fullPath: '/lookbook/'
      preLoaderRoute: typeof LookbookIndexRouteImport
      parentRoute: typeof LookbookRoute
    }
    '/frass-kicks/': {
      id: '/frass-kicks/'
      path: '/'
      fullPath: '/frass-kicks/'
      preLoaderRoute: typeof FrassKicksIndexRouteImport
      parentRoute: typeof FrassKicksRoute
    }
    '/frass-drip/': {
      id: '/frass-drip/'
      path: '/'
      fullPath: '/frass-drip/'
      preLoaderRoute: typeof FrassDripIndexRouteImport
      parentRoute: typeof FrassDripRoute
    }
    '/capsules/': {
      id: '/capsules/'
      path: '/'
      fullPath: '/capsules/'
      preLoaderRoute: typeof CapsulesIndexRouteImport
      parentRoute: typeof CapsulesRoute
    }
    '/blog/': {
      id: '/blog/'
      path: '/'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof BlogRoute
    }
    '/bare-drip/': {
      id: '/bare-drip/'
      path: '/'
      fullPath: '/bare-drip/'
      preLoaderRoute: typeof BareDripIndexRouteImport
      parentRoute: typeof BareDripRoute
    }
    '/afro-designers/': {
      id: '/afro-designers/'
      path: '/'
      fullPath: '/afro-designers/'
      preLoaderRoute: typeof AfroDesignersIndexRouteImport
      parentRoute: typeof AfroDesignersRoute
    }
    '/social-media-virals/$category': {
      id: '/social-media-virals/$category'
      path: '/$category'
      fullPath: '/social-media-virals/$category'
      preLoaderRoute: typeof SocialMediaViralsCategoryRouteImport
      parentRoute: typeof SocialMediaViralsRoute
    }
    '/product/$handle': {
      id: '/product/$handle'
      path: '/product/$handle'
      fullPath: '/product/$handle'
      preLoaderRoute: typeof ProductHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lookbook/$story': {
      id: '/lookbook/$story'
      path: '/$story'
      fullPath: '/lookbook/$story'
      preLoaderRoute: typeof LookbookStoryRouteImport
      parentRoute: typeof LookbookRoute
    }
    '/frass-kicks/women': {
      id: '/frass-kicks/women'
      path: '/women'
      fullPath: '/frass-kicks/women'
      preLoaderRoute: typeof FrassKicksWomenRouteImport
      parentRoute: typeof FrassKicksRoute
    }
    '/frass-kicks/men': {
      id: '/frass-kicks/men'
      path: '/men'
      fullPath: '/frass-kicks/men'
      preLoaderRoute: typeof FrassKicksMenRouteImport
      parentRoute: typeof FrassKicksRoute
    }
    '/frass-drip/women': {
      id: '/frass-drip/women'
      path: '/women'
      fullPath: '/frass-drip/women'
      preLoaderRoute: typeof FrassDripWomenRouteImport
      parentRoute: typeof FrassDripRoute
    }
    '/frass-drip/men': {
      id: '/frass-drip/men'
      path: '/men'
      fullPath: '/frass-drip/men'
      preLoaderRoute: typeof FrassDripMenRouteImport
      parentRoute: typeof FrassDripRoute
    }
    '/collection/$handle': {
      id: '/collection/$handle'
      path: '/collection/$handle'
      fullPath: '/collection/$handle'
      preLoaderRoute: typeof CollectionHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/capsules/$handle': {
      id: '/capsules/$handle'
      path: '/$handle'
      fullPath: '/capsules/$handle'
      preLoaderRoute: typeof CapsulesHandleRouteImport
      parentRoute: typeof CapsulesRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/bare-drip/women': {
      id: '/bare-drip/women'
      path: '/women'
      fullPath: '/bare-drip/women'
      preLoaderRoute: typeof BareDripWomenRouteImport
      parentRoute: typeof BareDripRoute
    }
    '/bare-drip/men': {
      id: '/bare-drip/men'
      path: '/men'
      fullPath: '/bare-drip/men'
      preLoaderRoute: typeof BareDripMenRouteImport
      parentRoute: typeof BareDripRoute
    }
    '/api/tts': {
      id: '/api/tts'
      path: '/api/tts'
      fullPath: '/api/tts'
      preLoaderRoute: typeof ApiTtsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/afro-designers/designers': {
      id: '/afro-designers/designers'
      path: '/designers'
      fullPath: '/afro-designers/designers'
      preLoaderRoute: typeof AfroDesignersDesignersRouteImport
      parentRoute: typeof AfroDesignersRoute
    }
    '/_authenticated/workspace': {
      id: '/_authenticated/workspace'
      path: '/workspace'
      fullPath: '/workspace'
      preLoaderRoute: typeof AuthenticatedWorkspaceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/try-on': {
      id: '/_authenticated/try-on'
      path: '/try-on'
      fullPath: '/try-on'
      preLoaderRoute: typeof AuthenticatedTryOnRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/frassy': {
      id: '/_authenticated/frassy'
      path: '/frassy'
      fullPath: '/frassy'
      preLoaderRoute: typeof AuthenticatedFrassyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/frass-drip/women/': {
      id: '/frass-drip/women/'
      path: '/'
      fullPath: '/frass-drip/women/'
      preLoaderRoute: typeof FrassDripWomenIndexRouteImport
      parentRoute: typeof FrassDripWomenRoute
    }
    '/frass-drip/men/': {
      id: '/frass-drip/men/'
      path: '/'
      fullPath: '/frass-drip/men/'
      preLoaderRoute: typeof FrassDripMenIndexRouteImport
      parentRoute: typeof FrassDripMenRoute
    }
    '/bare-drip/women/': {
      id: '/bare-drip/women/'
      path: '/'
      fullPath: '/bare-drip/women/'
      preLoaderRoute: typeof BareDripWomenIndexRouteImport
      parentRoute: typeof BareDripWomenRoute
    }
    '/bare-drip/men/': {
      id: '/bare-drip/men/'
      path: '/'
      fullPath: '/bare-drip/men/'
      preLoaderRoute: typeof BareDripMenIndexRouteImport
      parentRoute: typeof BareDripMenRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/social-media-virals/$category/$sub': {
      id: '/social-media-virals/$category/$sub'
      path: '/$sub'
      fullPath: '/social-media-virals/$category/$sub'
      preLoaderRoute: typeof SocialMediaViralsCategorySubRouteImport
      parentRoute: typeof SocialMediaViralsCategoryRoute
    }
    '/frass-drip/women/$category': {
      id: '/frass-drip/women/$category'
      path: '/$category'
      fullPath: '/frass-drip/women/$category'
      preLoaderRoute: typeof FrassDripWomenCategoryRouteImport
      parentRoute: typeof FrassDripWomenRoute
    }
    '/frass-drip/men/$category': {
      id: '/frass-drip/men/$category'
      path: '/$category'
      fullPath: '/frass-drip/men/$category'
      preLoaderRoute: typeof FrassDripMenCategoryRouteImport
      parentRoute: typeof FrassDripMenRoute
    }
    '/bare-drip/women/$category': {
      id: '/bare-drip/women/$category'
      path: '/$category'
      fullPath: '/bare-drip/women/$category'
      preLoaderRoute: typeof BareDripWomenCategoryRouteImport
      parentRoute: typeof BareDripWomenRoute
    }
    '/bare-drip/men/$category': {
      id: '/bare-drip/men/$category'
      path: '/$category'
      fullPath: '/bare-drip/men/$category'
      preLoaderRoute: typeof BareDripMenCategoryRouteImport
      parentRoute: typeof BareDripMenRoute
    }
    '/afro-designers/designers/$slug': {
      id: '/afro-designers/designers/$slug'
      path: '/$slug'
      fullPath: '/afro-designers/designers/$slug'
      preLoaderRoute: typeof AfroDesignersDesignersSlugRouteImport
      parentRoute: typeof AfroDesignersDesignersRoute
    }
    '/afro-designers/collections/$slug': {
      id: '/afro-designers/collections/$slug'
      path: '/collections/$slug'
      fullPath: '/afro-designers/collections/$slug'
      preLoaderRoute: typeof AfroDesignersCollectionsSlugRouteImport
      parentRoute: typeof AfroDesignersRoute
    }
    '/_authenticated/admin/visual-index': {
      id: '/_authenticated/admin/visual-index'
      path: '/visual-index'
      fullPath: '/admin/visual-index'
      preLoaderRoute: typeof AuthenticatedAdminVisualIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/virals': {
      id: '/_authenticated/admin/virals'
      path: '/virals'
      fullPath: '/admin/virals'
      preLoaderRoute: typeof AuthenticatedAdminViralsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/text': {
      id: '/_authenticated/admin/text'
      path: '/text'
      fullPath: '/admin/text'
      preLoaderRoute: typeof AuthenticatedAdminTextRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/roles': {
      id: '/_authenticated/admin/roles'
      path: '/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof AuthenticatedAdminRolesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/partner-vendors': {
      id: '/_authenticated/admin/partner-vendors'
      path: '/partner-vendors'
      fullPath: '/admin/partner-vendors'
      preLoaderRoute: typeof AuthenticatedAdminPartnerVendorsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/media': {
      id: '/_authenticated/admin/media'
      path: '/media'
      fullPath: '/admin/media'
      preLoaderRoute: typeof AuthenticatedAdminMediaRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/images': {
      id: '/_authenticated/admin/images'
      path: '/images'
      fullPath: '/admin/images'
      preLoaderRoute: typeof AuthenticatedAdminImagesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/cj-import': {
      id: '/_authenticated/admin/cj-import'
      path: '/cj-import'
      fullPath: '/admin/cj-import'
      preLoaderRoute: typeof AuthenticatedAdminCjImportRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/capsules': {
      id: '/_authenticated/admin/capsules'
      path: '/capsules'
      fullPath: '/admin/capsules'
      preLoaderRoute: typeof AuthenticatedAdminCapsulesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/blog': {
      id: '/_authenticated/admin/blog'
      path: '/blog'
      fullPath: '/admin/blog'
      preLoaderRoute: typeof AuthenticatedAdminBlogRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/approvals': {
      id: '/_authenticated/admin/approvals'
      path: '/approvals'
      fullPath: '/admin/approvals'
      preLoaderRoute: typeof AuthenticatedAdminApprovalsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/social-media-virals/$category/$sub/$product': {
      id: '/social-media-virals/$category/$sub/$product'
      path: '/$product'
      fullPath: '/social-media-virals/$category/$sub/$product'
      preLoaderRoute: typeof SocialMediaViralsCategorySubProductRouteImport
      parentRoute: typeof SocialMediaViralsCategorySubRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminApprovalsRoute: typeof AuthenticatedAdminApprovalsRoute
  AuthenticatedAdminBlogRoute: typeof AuthenticatedAdminBlogRoute
  AuthenticatedAdminCapsulesRoute: typeof AuthenticatedAdminCapsulesRoute
  AuthenticatedAdminCjImportRoute: typeof AuthenticatedAdminCjImportRoute
  AuthenticatedAdminImagesRoute: typeof AuthenticatedAdminImagesRoute
  AuthenticatedAdminMediaRoute: typeof AuthenticatedAdminMediaRoute
  AuthenticatedAdminPartnerVendorsRoute: typeof AuthenticatedAdminPartnerVendorsRoute
  AuthenticatedAdminRolesRoute: typeof AuthenticatedAdminRolesRoute
  AuthenticatedAdminTextRoute: typeof AuthenticatedAdminTextRoute
  AuthenticatedAdminViralsRoute: typeof AuthenticatedAdminViralsRoute
  AuthenticatedAdminVisualIndexRoute: typeof AuthenticatedAdminVisualIndexRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminApprovalsRoute: AuthenticatedAdminApprovalsRoute,
  AuthenticatedAdminBlogRoute: AuthenticatedAdminBlogRoute,
  AuthenticatedAdminCapsulesRoute: AuthenticatedAdminCapsulesRoute,
  AuthenticatedAdminCjImportRoute: AuthenticatedAdminCjImportRoute,
  AuthenticatedAdminImagesRoute: AuthenticatedAdminImagesRoute,
  AuthenticatedAdminMediaRoute: AuthenticatedAdminMediaRoute,
  AuthenticatedAdminPartnerVendorsRoute: AuthenticatedAdminPartnerVendorsRoute,
  AuthenticatedAdminRolesRoute: AuthenticatedAdminRolesRoute,
  AuthenticatedAdminTextRoute: AuthenticatedAdminTextRoute,
  AuthenticatedAdminViralsRoute: AuthenticatedAdminViralsRoute,
  AuthenticatedAdminVisualIndexRoute: AuthenticatedAdminVisualIndexRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedFrassyRoute: typeof AuthenticatedFrassyRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedTryOnRoute: typeof AuthenticatedTryOnRoute
  AuthenticatedWorkspaceRoute: typeof AuthenticatedWorkspaceRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedFrassyRoute: AuthenticatedFrassyRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedTryOnRoute: AuthenticatedTryOnRoute,
  AuthenticatedWorkspaceRoute: AuthenticatedWorkspaceRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AfroDesignersDesignersRouteChildren {
  AfroDesignersDesignersSlugRoute: typeof AfroDesignersDesignersSlugRoute
}

const AfroDesignersDesignersRouteChildren: AfroDesignersDesignersRouteChildren =
  {
    AfroDesignersDesignersSlugRoute: AfroDesignersDesignersSlugRoute,
  }

const AfroDesignersDesignersRouteWithChildren =
  AfroDesignersDesignersRoute._addFileChildren(
    AfroDesignersDesignersRouteChildren,
  )

interface AfroDesignersRouteChildren {
  AfroDesignersDesignersRoute: typeof AfroDesignersDesignersRouteWithChildren
  AfroDesignersIndexRoute: typeof AfroDesignersIndexRoute
  AfroDesignersCollectionsSlugRoute: typeof AfroDesignersCollectionsSlugRoute
}

const AfroDesignersRouteChildren: AfroDesignersRouteChildren = {
  AfroDesignersDesignersRoute: AfroDesignersDesignersRouteWithChildren,
  AfroDesignersIndexRoute: AfroDesignersIndexRoute,
  AfroDesignersCollectionsSlugRoute: AfroDesignersCollectionsSlugRoute,
}

const AfroDesignersRouteWithChildren = AfroDesignersRoute._addFileChildren(
  AfroDesignersRouteChildren,
)

interface BareDripMenRouteChildren {
  BareDripMenCategoryRoute: typeof BareDripMenCategoryRoute
  BareDripMenIndexRoute: typeof BareDripMenIndexRoute
}

const BareDripMenRouteChildren: BareDripMenRouteChildren = {
  BareDripMenCategoryRoute: BareDripMenCategoryRoute,
  BareDripMenIndexRoute: BareDripMenIndexRoute,
}

const BareDripMenRouteWithChildren = BareDripMenRoute._addFileChildren(
  BareDripMenRouteChildren,
)

interface BareDripWomenRouteChildren {
  BareDripWomenCategoryRoute: typeof BareDripWomenCategoryRoute
  BareDripWomenIndexRoute: typeof BareDripWomenIndexRoute
}

const BareDripWomenRouteChildren: BareDripWomenRouteChildren = {
  BareDripWomenCategoryRoute: BareDripWomenCategoryRoute,
  BareDripWomenIndexRoute: BareDripWomenIndexRoute,
}

const BareDripWomenRouteWithChildren = BareDripWomenRoute._addFileChildren(
  BareDripWomenRouteChildren,
)

interface BareDripRouteChildren {
  BareDripMenRoute: typeof BareDripMenRouteWithChildren
  BareDripWomenRoute: typeof BareDripWomenRouteWithChildren
  BareDripIndexRoute: typeof BareDripIndexRoute
}

const BareDripRouteChildren: BareDripRouteChildren = {
  BareDripMenRoute: BareDripMenRouteWithChildren,
  BareDripWomenRoute: BareDripWomenRouteWithChildren,
  BareDripIndexRoute: BareDripIndexRoute,
}

const BareDripRouteWithChildren = BareDripRoute._addFileChildren(
  BareDripRouteChildren,
)

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface CapsulesRouteChildren {
  CapsulesHandleRoute: typeof CapsulesHandleRoute
  CapsulesIndexRoute: typeof CapsulesIndexRoute
}

const CapsulesRouteChildren: CapsulesRouteChildren = {
  CapsulesHandleRoute: CapsulesHandleRoute,
  CapsulesIndexRoute: CapsulesIndexRoute,
}

const CapsulesRouteWithChildren = CapsulesRoute._addFileChildren(
  CapsulesRouteChildren,
)

interface FrassDripMenRouteChildren {
  FrassDripMenCategoryRoute: typeof FrassDripMenCategoryRoute
  FrassDripMenIndexRoute: typeof FrassDripMenIndexRoute
}

const FrassDripMenRouteChildren: FrassDripMenRouteChildren = {
  FrassDripMenCategoryRoute: FrassDripMenCategoryRoute,
  FrassDripMenIndexRoute: FrassDripMenIndexRoute,
}

const FrassDripMenRouteWithChildren = FrassDripMenRoute._addFileChildren(
  FrassDripMenRouteChildren,
)

interface FrassDripWomenRouteChildren {
  FrassDripWomenCategoryRoute: typeof FrassDripWomenCategoryRoute
  FrassDripWomenIndexRoute: typeof FrassDripWomenIndexRoute
}

const FrassDripWomenRouteChildren: FrassDripWomenRouteChildren = {
  FrassDripWomenCategoryRoute: FrassDripWomenCategoryRoute,
  FrassDripWomenIndexRoute: FrassDripWomenIndexRoute,
}

const FrassDripWomenRouteWithChildren = FrassDripWomenRoute._addFileChildren(
  FrassDripWomenRouteChildren,
)

interface FrassDripRouteChildren {
  FrassDripMenRoute: typeof FrassDripMenRouteWithChildren
  FrassDripWomenRoute: typeof FrassDripWomenRouteWithChildren
  FrassDripIndexRoute: typeof FrassDripIndexRoute
}

const FrassDripRouteChildren: FrassDripRouteChildren = {
  FrassDripMenRoute: FrassDripMenRouteWithChildren,
  FrassDripWomenRoute: FrassDripWomenRouteWithChildren,
  FrassDripIndexRoute: FrassDripIndexRoute,
}

const FrassDripRouteWithChildren = FrassDripRoute._addFileChildren(
  FrassDripRouteChildren,
)

interface FrassKicksRouteChildren {
  FrassKicksMenRoute: typeof FrassKicksMenRoute
  FrassKicksWomenRoute: typeof FrassKicksWomenRoute
  FrassKicksIndexRoute: typeof FrassKicksIndexRoute
}

const FrassKicksRouteChildren: FrassKicksRouteChildren = {
  FrassKicksMenRoute: FrassKicksMenRoute,
  FrassKicksWomenRoute: FrassKicksWomenRoute,
  FrassKicksIndexRoute: FrassKicksIndexRoute,
}

const FrassKicksRouteWithChildren = FrassKicksRoute._addFileChildren(
  FrassKicksRouteChildren,
)

interface LookbookRouteChildren {
  LookbookStoryRoute: typeof LookbookStoryRoute
  LookbookIndexRoute: typeof LookbookIndexRoute
}

const LookbookRouteChildren: LookbookRouteChildren = {
  LookbookStoryRoute: LookbookStoryRoute,
  LookbookIndexRoute: LookbookIndexRoute,
}

const LookbookRouteWithChildren = LookbookRoute._addFileChildren(
  LookbookRouteChildren,
)

interface SocialMediaViralsCategorySubRouteChildren {
  SocialMediaViralsCategorySubProductRoute: typeof SocialMediaViralsCategorySubProductRoute
}

const SocialMediaViralsCategorySubRouteChildren: SocialMediaViralsCategorySubRouteChildren =
  {
    SocialMediaViralsCategorySubProductRoute:
      SocialMediaViralsCategorySubProductRoute,
  }

const SocialMediaViralsCategorySubRouteWithChildren =
  SocialMediaViralsCategorySubRoute._addFileChildren(
    SocialMediaViralsCategorySubRouteChildren,
  )

interface SocialMediaViralsCategoryRouteChildren {
  SocialMediaViralsCategorySubRoute: typeof SocialMediaViralsCategorySubRouteWithChildren
}

const SocialMediaViralsCategoryRouteChildren: SocialMediaViralsCategoryRouteChildren =
  {
    SocialMediaViralsCategorySubRoute:
      SocialMediaViralsCategorySubRouteWithChildren,
  }

const SocialMediaViralsCategoryRouteWithChildren =
  SocialMediaViralsCategoryRoute._addFileChildren(
    SocialMediaViralsCategoryRouteChildren,
  )

interface SocialMediaViralsRouteChildren {
  SocialMediaViralsCategoryRoute: typeof SocialMediaViralsCategoryRouteWithChildren
  SocialMediaViralsIndexRoute: typeof SocialMediaViralsIndexRoute
}

const SocialMediaViralsRouteChildren: SocialMediaViralsRouteChildren = {
  SocialMediaViralsCategoryRoute: SocialMediaViralsCategoryRouteWithChildren,
  SocialMediaViralsIndexRoute: SocialMediaViralsIndexRoute,
}

const SocialMediaViralsRouteWithChildren =
  SocialMediaViralsRoute._addFileChildren(SocialMediaViralsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AfroDesignersRoute: AfroDesignersRouteWithChildren,
  AuthRoute: AuthRoute,
  BareDripRoute: BareDripRouteWithChildren,
  BlogRoute: BlogRouteWithChildren,
  CapsulesRoute: CapsulesRouteWithChildren,
  CheckoutRoute: CheckoutRoute,
  FrassDripRoute: FrassDripRouteWithChildren,
  FrassKicksRoute: FrassKicksRouteWithChildren,
  LookbookRoute: LookbookRouteWithChildren,
  McpRoute: McpRoute,
  MusicMediaRoute: MusicMediaRoute,
  RewardsRoute: RewardsRoute,
  SocialMediaViralsRoute: SocialMediaViralsRouteWithChildren,
  VisualSearchRoute: VisualSearchRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  ApiChatRoute: ApiChatRoute,
  ApiTtsRoute: ApiTtsRoute,
  CollectionHandleRoute: CollectionHandleRoute,
  ProductHandleRoute: ProductHandleRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
